resolver: lts-8.0
packages:
- srv
- tools/vinnie
- caroperator-svc
- carma-models
- carma-mobile-server
- carma-http
- carma-dict
- location:
    git: git@github.com:f-me/dmcc.git
    commit: ba5ad3c1d57f60e248a5d5b2c1be808db00825ae
  extra-dep: true
- location:
    git: git@github.com:f-me/hs-weather-api.git
    commit: 6256f3925bdf324b696559bb75b900c544599784
  extra-dep: true
- location:
    git: git@github.com:f-me/pg-simple-alt-qq.git
    commit: 15fd5b959f0d88a50d2c460938bdb0cd2cd7322d
  extra-dep: true
- location:
    git: git@github.com:mulderr/snap-core.git
    commit: a0c0981ef5e9aba8fec4d5db7f808b58f2615f29
  extra-dep: true
- location:
    git: git@github.com:Soostone/snaplet-persistent.git
    commit: 27c30f24bdff3f801fda47f30d483ca154708674
  extra-dep: true
extra-deps:
- attoparsec-conduit-1.1.0
- digestive-functors-0.8.2.0
- digestive-functors-heist-0.8.7.0
- digestive-functors-snap-0.7.0.0
- map-syntax-0.2.0.2
- heist-1.0.1.0
- qm-interpolated-string-0.1.1.0
- snap-1.0.0.1
- snap-extras-0.12.0.0
- snap-loader-static-1.0.0.0
- snaplet-postgresql-simple-1.0.2.0
image:
  containers:
    - base: "formalmethods/carma-base-runtime"
