resolver: lts-3.12
packages:
- srv
- tools/vinnie
- caroperator-svc
- carma-models
- carma-mobile-server
- carma-http
- carma-dict
- location:
    git: git@github.com:f-me/dmcc.git
    commit: ba5ad3c1d57f60e248a5d5b2c1be808db00825ae
  extra-dep: true
- location:
    git: git@github.com:f-me/hs-weather-api.git
    commit: 6256f3925bdf324b696559bb75b900c544599784
  extra-dep: true
- location:
    git: git@github.com:f-me/pg-simple-alt-qq.git
    commit: 15fd5b959f0d88a50d2c460938bdb0cd2cd7322d
  extra-dep: true
- location:
    git: git@github.com:f-me/snap-core.git
    commit: 1732b6ff0325b68a93dd9e07ac618f4d5e2cd527
  extra-dep: true
extra-deps:
- attoparsec-conduit-1.1.0
- digestive-functors-heist-0.8.6.2
- digestive-functors-snap-0.6.1.3
- graphviz-2999.18.0.2
- qm-interpolated-string-0.1.1.0
- readable-0.3.1
- resource-pool-catchio-0.2.1.0
- snap-extras-0.11.0.2
- snap-loader-static-0.9.0.2
- snaplet-postgresql-simple-0.6.0.4
- websockets-snap-0.9.2.0
image:
  containers:
    - base: "formalmethods/carma-base-runtime"
