resolver: lts-3.12
packages:
- srv
- tools/vinnie
- location:
    git: git@github.com:f-me/carma-models.git
    commit: origin/rc
  extra-dep: true
- location:
    git: git@github.com:f-me/dmcc.git
    commit: HEAD
  extra-dep: true
- location:
    git: git@github.com:f-me/hs-weather-api.git
    commit: HEAD
  extra-dep: true
- location:
    git: git@github.com:f-me/pg-simple-alt-qq.git
    commit: origin/stack
  extra-dep: true
extra-deps:
- attoparsec-conduit-1.1.0
- digestive-functors-heist-0.8.6.2
- digestive-functors-snap-0.6.1.3
- graphviz-2999.18.0.2
- readable-0.3.1
- resource-pool-catchio-0.2.1.0
- snap-extras-0.11.0.2
- snap-loader-static-0.9.0.2
- snaplet-postgresql-simple-0.6.0.4
- websockets-snap-0.9.2.0
