name: carma-casepartner-us
version: 0.1
license: BSD3
author: Alexander Danilov
maintainer: alexander.a.danilov@gmail.com
category: web
synopsis: Case partner manager microservice

description:
  Case partner manager application backend.

dependencies:
  - aeson
  - attoparsec
  - base
  - basic-prelude
  - bytestring
  - carma-models
  - carma-http
  - carma-model-utils
  - carma-utils
  - clientsession
  - configurator
  - containers
  - directory
  - filepath
  - HTTP >= 4000.3.9
  - hsyslog
  - io-streams >= 1.5.1.0
  - lens
  - lifted-base
  - map-syntax
  - monad-control
  - mtl
  - pg-simple-qq-alt
  - postgresql-simple >= 0.6.2
  - snap
  - snap-core
  - snap-loader-static
  - snap-server
  - snaplet-postgresql-simple
  - temporary >= 1.3
  - text
  - time
  - unordered-containers
  - vector
  - xmlhtml

default-extensions:
  - CPP
  - DeriveAnyClass
  - DeriveDataTypeable
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - OverloadedStrings
  - QuasiQuotes
  - ScopedTypeVariables
  - TemplateHaskell
  - TypeOperators
  - ConstraintKinds
  - DataKinds
  - DeriveDataTypeable
  - ExistentialQuantification
  - MultiWayIf
  - ScopedTypeVariables
  - TypeFamilies


ghc-options:
  - -O2
  - -Wall
  - -Werror
  - -fno-warn-orphans
  - -fno-warn-unused-do-bind
  - -funbox-strict-fields
  - -fwarn-tabs

library:
  source-dirs: src

executables:
  carma-casepartner-us:
    source-dirs: src
    main: Main.hs
    dependencies: [carma-casepartner-us]
    ghc-options: [-threaded]

