version: 2

defaults: &defaults
  working_directory: "/carma"

jobs:

  build_client:
    <<: *defaults
    docker:
      - image: node:4.8.4
    steps:
      - checkout
      - run:
          name: Build CaRMa frontend
          command: |
            cd srv
            npm install -g grunt
            npm install
            cd resources/assets/react-components
            npm install
            cd -
            mkdir -p resources/static/{js/gen,css}
            # TODO webpack build
      - persist_to_workspace:
          root: .
          paths:
            - ./srv/resources

  build_server:
    <<: *defaults
    docker:
      - image: formalmethods/carma-stack-build:stack-1.6.3@sha256:13b265472181d1c519420aff8dbe2e8426da52e41094e4c9e70004caac4004ae
    steps:
      - setup_remote_docker
      - checkout
      - restore_cache:
          keys:
            - stack-cache-{{ checksum "stack.yaml" }}
      - run:
          name: Build CaRMa backend
          command: |
            stack --install-ghc -j2 build
      - save_cache:
          key: stack-cache-{{ checksum "stack.yaml" }}
          paths:
            - ~/.cabal
            - ~/.ghc
            - ~/.stack
            - .stack-work
      - run:
          name: Build CaRMa backend container
          command: |
            stack image container
            docker save carma > carma-image.tar
      - persist_to_workspace:
          root: .
          paths:
            - ./carma-image.tar

  build_bundle:
    <<: *defaults
    docker:
      - image: formalmethods/carma-stack-build:stack-1.6.3@sha256:13b265472181d1c519420aff8dbe2e8426da52e41094e4c9e70004caac4004ae
    steps:
      - setup_remote_docker
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build CaRMa frontend + backend container
          command: |
            docker load < carma-image.tar
            cd srv
            docker build \
              --build-arg VCS_REF=$CIRCLE_SHA1 \
              --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
              -t formalmethods/carma-bundle:latest \
              -t formalmethods/carma-bundle:${CIRCLE_BRANCH/\//-} \
              -t formalmethods/carma-bundle:$CIRCLE_SHA1 \
              .

      - run:
          name: Push to Docker Hub
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            if [ $CIRCLE_BRANCH = "master" ]; then docker push formalmethods/carma-bundle:latest; fi
            docker push formalmethods/carma-bundle:${CIRCLE_BRANCH/\//-}
            docker push formalmethods/carma-bundle:$CIRCLE_SHA1
            docker logout

workflows:
  version: 2
  build_all:
    jobs:
      - build_client
      - build_server
      - build_bundle:
          requires:
            - build_client
            - build_server
